/* eslint-disable @typescript-eslint/no-unsafe-member-access */
/* eslint-disable @typescript-eslint/no-unsafe-assignment */
/* eslint-disable @typescript-eslint/ban-ts-comment */
/* eslint-disable @next/next/no-sync-scripts */
/* eslint-disable react/jsx-no-comment-textnodes */
import Head from "next/head";
import { useEffect } from "react";
// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  useEffect(() => {
    const otplessDiv = document.createElement("div");
    otplessDiv.id = "otpless";
    document.getElementsByClassName("otpless")[0]?.appendChild(otplessDiv);

    // Define the 'otpless' function
    // @ts-ignore
    window.otpless = (otplessUser) => {
      // Retrieve the user's details after successful login
      // eslint-disable-next-line @typescript-eslint/no-unsafe-member-access
      const waName = otplessUser.waName;
      const waNumber = otplessUser.waNumber;
      console.log(waName, waNumber);
      // Handle the signup/signin process
      // ...
    };
    return () => {
      document.getElementsByClassName("otpless")[0]?.appendChild(otplessDiv);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

        <script
          type="text/javascript"
          src="https://otpless.com/auth.js"
        ></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="otpless"></div>
      </main>
    </>
  );
}
